import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import ReduxProvider from "@/lib/ProviderRedux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fitness Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <ReduxProvider>{children}</ReduxProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
