import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import "./globals.css";
import ReduxProvider from "@/lib/ProviderRedux";
import trTR from "antd/locale/tr_TR";
import "dayjs/locale/tr";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fitness Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider locale={trTR}>
          <AntdRegistry>
            <ReduxProvider>{children}</ReduxProvider>
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
